<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MacMakeover.Supervisor</AssemblyName>
    <RootNamespace>MacMakeover.Supervisor</RootNamespace>
    <Product>Vesper Shell</Product>
    <AssemblyTitle>Vesper Supervisor</AssemblyTitle>
    <Description>Vesper Shell Supervisor</Description>
    <PublishSingleFile>true</PublishSingleFile>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
